/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Intefaz;

/**
 *
 * @author junom
 */
import controladores.Controlador_Global;

public class AlumnosUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AlumnosUI.class.getName());
    private Controlador_Global GC;

    /**
     * Creates new form AlumnosUI
     */
    public AlumnosUI() {
        initComponents();
    }
    public AlumnosUI(Controlador_Global GC) {
        initComponents();
        GC = GC;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        vtnReservarAlumnos = new javax.swing.JMenu();
        jmiReservar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        vtnRealiarPagoAlumnos = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        vtnHistorialAlumnos = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        vtnActualizarAlumnos = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 403, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );

        vtnReservarAlumnos.setText("Clases");

        jmiReservar.setText("Reservar");
        jmiReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiReservarActionPerformed(evt);
            }
        });
        vtnReservarAlumnos.add(jmiReservar);

        jMenuBar1.add(vtnReservarAlumnos);

        jMenu3.setText("Adeudos");

        vtnRealiarPagoAlumnos.setText("Realizar pago");
        vtnRealiarPagoAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vtnRealiarPagoAlumnosActionPerformed(evt);
            }
        });
        jMenu3.add(vtnRealiarPagoAlumnos);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Asistencias");

        vtnHistorialAlumnos.setText("Historial");
        vtnHistorialAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vtnHistorialAlumnosActionPerformed(evt);
            }
        });
        jMenu4.add(vtnHistorialAlumnos);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Yo");

        vtnActualizarAlumnos.setText("Actualizar mis datos");
        vtnActualizarAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vtnActualizarAlumnosActionPerformed(evt);
            }
        });
        jMenu5.add(vtnActualizarAlumnos);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiReservarActionPerformed
        // TODO add your handling code here:
        
        ReservarClasesAlumno ventanaReservarClaseAlumno = new ReservarClasesAlumno();
        jDesktopPane1.add(ventanaReservarClaseAlumno);
        ventanaReservarClaseAlumno.show();
    }//GEN-LAST:event_jmiReservarActionPerformed

    private void vtnRealiarPagoAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vtnRealiarPagoAlumnosActionPerformed
        // TODO add your handling code here:
        PagoAlumnos  ventanaPagoAlumno = new PagoAlumnos(GC);
        jDesktopPane1.add(ventanaPagoAlumno);
        ventanaPagoAlumno.show();
        
    }//GEN-LAST:event_vtnRealiarPagoAlumnosActionPerformed

    private void vtnHistorialAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vtnHistorialAlumnosActionPerformed
        // TODO add your handling code here:
        HistorialAsistencias  Historial = new HistorialAsistencias(GC);
        jDesktopPane1.add(Historial);
        Historial.show();
        
    
    }//GEN-LAST:event_vtnHistorialAlumnosActionPerformed

    private void vtnActualizarAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vtnActualizarAlumnosActionPerformed
        // TODO add your handling code here:
        ActualizarDatosAlumno  ActualizarAlumno = new ActualizarDatosAlumno();
        jDesktopPane1.add(ActualizarAlumno);
        ActualizarAlumno.show();
       
    }//GEN-LAST:event_vtnActualizarAlumnosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AlumnosUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jmiReservar;
    private javax.swing.JMenuItem vtnActualizarAlumnos;
    private javax.swing.JMenuItem vtnHistorialAlumnos;
    private javax.swing.JMenuItem vtnRealiarPagoAlumnos;
    private javax.swing.JMenu vtnReservarAlumnos;
    // End of variables declaration//GEN-END:variables
}
