/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Intefaz;

import controladores.Controlador_Global;
import javax.swing.JOptionPane;

/**
 *
 * @author junom
 */
public class AsistenciasProfesores extends javax.swing.JInternalFrame {
    Controlador_Global CG;

    /**
     * Creates new form AsistenciasProfesores
     */
    public AsistenciasProfesores() {
        initComponents();
    }
    public AsistenciasProfesores(Controlador_Global Gc) {
        this.CG = Gc;
        initComponents();
        cargarListas();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtlistAlumnos = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlistClase = new javax.swing.JList<>();
        jbnConfirmarAsistencia = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Birds of Paradise  Personal use", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Asistencias");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe Script", 0, 12)); // NOI18N
        jLabel2.setText("Alumnos");

        jtlistAlumnos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jtlistAlumnos);

        jLabel3.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jLabel3.setText("Clase");

        jlistClase.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jlistClase);

        jbnConfirmarAsistencia.setBackground(new java.awt.Color(0, 0, 0));
        jbnConfirmarAsistencia.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jbnConfirmarAsistencia.setForeground(new java.awt.Color(255, 255, 255));
        jbnConfirmarAsistencia.setText("Asistieron");
        jbnConfirmarAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnConfirmarAsistenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jbnConfirmarAsistencia)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(110, 110, 110))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jbnConfirmarAsistencia)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbnConfirmarAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnConfirmarAsistenciaActionPerformed
        confirmarAsistencia();
    }//GEN-LAST:event_jbnConfirmarAsistenciaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbnConfirmarAsistencia;
    private javax.swing.JList<String> jlistClase;
    private javax.swing.JList<String> jtlistAlumnos;
    // End of variables declaration//GEN-END:variables

    private void cargarListas() {

        int totalAlumnos = 0;
        for (int i = 0; i < CG.CA_A.Asignaciones.length; i++) {
            if (CG.CA_A.Asignaciones[i] != null) totalAlumnos++;
        }
        
        String[] alumnos = new String[totalAlumnos];
        int posA = 0;

        for (int i = 0; i < CG.CA_A.Asignaciones.length; i++) {
            if (CG.CA_A.Asignaciones[i] != null) {
                alumnos[posA] =
                        CG.CA_A.Asignaciones[i].getIdAlumno()
                        + " - Alumno";
                posA++;
            }
        }

        jtlistAlumnos.setListData(alumnos);


        // ----------- CARGAR CLASES DEL PROFESOR -----------

        int idProfesor = CG.getUsuarioSesion().getId();

        int totalClases = 0;
        for (int i = 0; i < CG.CA_P.Asignaciones.length; i++) {
            if (CG.CA_P.Asignaciones[i] != null
                    && CG.CA_P.Asignaciones[i].getIdProfesor() == idProfesor) {
                totalClases++;
            }
        }

        String[] clases = new String[totalClases];
        int posC = 0;

        for (int i = 0; i < CG.CA_P.Asignaciones.length; i++) {
            if (CG.CA_P.Asignaciones[i] != null
                    && CG.CA_P.Asignaciones[i].getIdProfesor() == idProfesor) {

                clases[posC] =
                        CG.CA_P.Asignaciones[i].getIdClase()
                        + " - Clase Asignada";

                posC++;
            }
        }

        jlistClase.setListData(clases);
    }
    
     private void confirmarAsistencia() {

        String alumnoSel = jtlistAlumnos.getSelectedValue();
        String claseSel = jlistClase.getSelectedValue();

        if (alumnoSel == null || claseSel == null) {
            JOptionPane.showMessageDialog(this, "Selecciona un alumno y una clase.");
            return;
        }

        int idAlumno = Integer.parseInt(alumnoSel.split(" - ")[0]);
        int idClase = Integer.parseInt(claseSel.split(" - ")[0]);

        // SUMAR ASISTENCIA AL ALUMNO
        boolean exitoA = CG.CA_A.SumarAsistencia(idAlumno);

        // SUMAR ASISTENCIA AL PROFESOR
        int idProfesor = CG.getUsuarioSesion().getId();
        
        boolean exitoP = CG.CA_P.SumarAsistencia(idProfesor);
        
        if (exitoA && exitoP) {
            JOptionPane.showMessageDialog(this, "Asistencia registrada correctamente.");
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo registrar la asistencia.");
        }
    }
}
