/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Intefaz;

/**
 *
 * @author junom
 */

import controladores.Controlador_Global;

public class DirectorUI extends javax.swing.JFrame {
    
    public Controlador_Global GC;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DirectorUI.class.getName());

    /**
     * Creates new form DirectorUI
     */
    public DirectorUI() {
        initComponents();
    }
    public DirectorUI(Controlador_Global Gc) {
        initComponents();
        GC = Gc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        vtnPagosDirector = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        vtnSupervisarDirector = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        vtnReportesDirector = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jmiGestionarClases = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        vtnGestionarAlumnos = new javax.swing.JMenuItem();
        Cerrar = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 694, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );

        jMenu2.setText("Pagos");

        vtnPagosDirector.setText("Gestionar Pagos");
        vtnPagosDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vtnPagosDirectorActionPerformed(evt);
            }
        });
        jMenu2.add(vtnPagosDirector);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Profesores");

        vtnSupervisarDirector.setText("Supervisar");
        vtnSupervisarDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vtnSupervisarDirectorActionPerformed(evt);
            }
        });
        jMenu3.add(vtnSupervisarDirector);

        jMenuBar1.add(jMenu3);

        jMenu6.setText("Reportes");

        vtnReportesDirector.setText("Ver Reportes");
        vtnReportesDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vtnReportesDirectorActionPerformed(evt);
            }
        });
        jMenu6.add(vtnReportesDirector);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Clases");

        jmiGestionarClases.setText("Gestionar");
        jmiGestionarClases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGestionarClasesActionPerformed(evt);
            }
        });
        jMenu7.add(jmiGestionarClases);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Alumnnos");

        vtnGestionarAlumnos.setText("Gestionar");
        vtnGestionarAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vtnGestionarAlumnosActionPerformed(evt);
            }
        });
        jMenu8.add(vtnGestionarAlumnos);

        jMenuBar1.add(jMenu8);

        Cerrar.setText("Cerrar sesion");
        Cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarMouseClicked(evt);
            }
        });
        jMenuBar1.add(Cerrar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void vtnPagosDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vtnPagosDirectorActionPerformed
        // TODO add your handling code here:
        PagoDirector  ventana = new PagoDirector(GC);
        jDesktopPane1.add(ventana);
        ventana.show();
    }//GEN-LAST:event_vtnPagosDirectorActionPerformed

    private void vtnSupervisarDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vtnSupervisarDirectorActionPerformed
        // TODO add your handling code here:
        ReportesDirector  ventana = new ReportesDirector(GC);
        jDesktopPane1.add(ventana);
        ventana.show();
        
    }//GEN-LAST:event_vtnSupervisarDirectorActionPerformed

    private void vtnReportesDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vtnReportesDirectorActionPerformed
        // TODO add your handling code here:
        SupervisarDirector  ventana = new SupervisarDirector(GC);
        jDesktopPane1.add(ventana);
        ventana.show();
    }//GEN-LAST:event_vtnReportesDirectorActionPerformed

    private void jmiGestionarClasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGestionarClasesActionPerformed
        // TODO add your handling code here:
        GestionarClasesDirector  ventanaGestionarClase = new GestionarClasesDirector(GC);
        jDesktopPane1.add(ventanaGestionarClase);
        ventanaGestionarClase.show();
    }//GEN-LAST:event_jmiGestionarClasesActionPerformed

    private void vtnGestionarAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vtnGestionarAlumnosActionPerformed
        // TODO add your handling code here:
        GestionarAlumnDirector  ventanaGestionarClase = new GestionarAlumnDirector(GC);
        jDesktopPane1.add(ventanaGestionarClase);
        ventanaGestionarClase.show();
    }//GEN-LAST:event_vtnGestionarAlumnosActionPerformed

    private void CerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CerrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DirectorUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Cerrar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jmiGestionarClases;
    private javax.swing.JMenuItem vtnGestionarAlumnos;
    private javax.swing.JMenuItem vtnPagosDirector;
    private javax.swing.JMenuItem vtnReportesDirector;
    private javax.swing.JMenuItem vtnSupervisarDirector;
    // End of variables declaration//GEN-END:variables
}
