/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Intefaz;

import java.awt.Color;
import javax.swing.UIManager;
import controladores.Controlador_Global;
/**
 *
 * @author junom
 */
public class ProfesoresUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProfesoresUI.class.getName());
    public Controlador_Global GC;
    /**
     * Creates new form ProfesoresUI
     */
    public ProfesoresUI() {
        initComponents();

        jMenuBar1.setOpaque(true);
        jMenuBar1.setBackground(Color.BLACK);
        jMenuBar1.setForeground(Color.WHITE);

        jMenu2.setForeground(Color.WHITE);
        jMenu3.setForeground(Color.WHITE);
        jMenu4.setForeground(Color.WHITE);

    }
    public ProfesoresUI(Controlador_Global Gc) {
        initComponents();
        GC = Gc;
        jMenuBar1.setOpaque(true);
        jMenuBar1.setBackground(Color.BLACK);
        jMenuBar1.setForeground(Color.WHITE);

        jMenu2.setForeground(Color.WHITE);
        jMenu3.setForeground(Color.WHITE);
        jMenu4.setForeground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem6 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        vtnClasesProfesores = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        vtnAsistenciasProfesor = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        vtnPagosProfesores = new javax.swing.JMenuItem();

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        jMenuBar1.setBorder(null);
        jMenuBar1.setBorderPainted(false);

        jMenu2.setText("Clases");

        vtnClasesProfesores.setText("ver clases");
        vtnClasesProfesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vtnClasesProfesoresActionPerformed(evt);
            }
        });
        jMenu2.add(vtnClasesProfesores);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Asistencias");

        vtnAsistenciasProfesor.setText("Anotar asistencias");
        vtnAsistenciasProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vtnAsistenciasProfesorActionPerformed(evt);
            }
        });
        jMenu3.add(vtnAsistenciasProfesor);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Yo");

        vtnPagosProfesores.setText("Pagos");
        vtnPagosProfesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vtnPagosProfesoresActionPerformed(evt);
            }
        });
        jMenu4.add(vtnPagosProfesores);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vtnClasesProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vtnClasesProfesoresActionPerformed
        // TODO add your handling code here:
        GestionarClasesProfesor interfaz = new GestionarClasesProfesor(GC,GC.getUsuarioSesion().getId()); 
        jDesktopPane1.add(interfaz);
        interfaz.show();
    }//GEN-LAST:event_vtnClasesProfesoresActionPerformed

    private void vtnAsistenciasProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vtnAsistenciasProfesorActionPerformed
        // TODO add your handling code here:
        AsistenciasProfesores interfaz = new AsistenciasProfesores(GC); 
        jDesktopPane1.add(interfaz);
        interfaz.show();
    }//GEN-LAST:event_vtnAsistenciasProfesorActionPerformed

    private void vtnPagosProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vtnPagosProfesoresActionPerformed
        // TODO add your handling code here:
        PagoProfesor interfaz = new PagoProfesor(GC); 
        jDesktopPane1.add(interfaz);
        interfaz.show();
    }//GEN-LAST:event_vtnPagosProfesoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        UIManager.put("MenuBar.background", Color.BLACK);
        UIManager.put("MenuBar.foreground", Color.WHITE);
        UIManager.put("Menu.foreground", Color.WHITE);
        UIManager.put("MenuItem.background", Color.BLACK);
        UIManager.put("MenuItem.foreground", Color.WHITE);
        UIManager.put("Menu.selectionBackground", Color.DARK_GRAY);
        UIManager.put("MenuItem.selectionBackground", Color.DARK_GRAY);

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ProfesoresUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem vtnAsistenciasProfesor;
    private javax.swing.JMenuItem vtnClasesProfesores;
    private javax.swing.JMenuItem vtnPagosProfesores;
    // End of variables declaration//GEN-END:variables
}
